version: 2

sources:
  - name: raw
    schema: raw_data_circle
    tables:
      - name: funnel
        identifier: raw_cc_funnel
      - name: priority
        identifier: raw_cc_funnel_priority

models:
  - name: stg_raw__priority
    columns:
      - name: priority
        tests:
          - accepted_values:
              values: ['Low', 'Medium', 'High']